#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 72
#define LARGE_STATE_COUNT 18
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 14

enum {
  sym__ws = 1,
  anon_sym_COLON = 2,
  aux_sym_keyword_token1 = 3,
  aux_sym_symbol_token1 = 4,
  anon_sym_CARET = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  sym_source = 10,
  sym__gap = 11,
  sym__form = 12,
  sym__metadata = 13,
  sym_vector = 14,
  sym_list = 15,
  sym__bare_list = 16,
  sym__bare_vector = 17,
  aux_sym_source_repeat1 = 18,
  aux_sym_keyword_repeat1 = 19,
  aux_sym__metadata_repeat1 = 20,
  aux_sym_vector_repeat1 = 21,
  aux_sym__bare_list_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__ws] = "_ws",
  [anon_sym_COLON] = ":",
  [aux_sym_keyword_token1] = "keyword_token1",
  [aux_sym_symbol_token1] = "symbol_token1",
  [anon_sym_CARET] = "^",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source] = "source",
  [sym__gap] = "_gap",
  [sym__form] = "_form",
  [sym__metadata] = "_metadata",
  [sym_vector] = "vector",
  [sym_list] = "list",
  [sym__bare_list] = "_bare_list",
  [sym__bare_vector] = "_bare_vector",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_keyword_repeat1] = "keyword_repeat1",
  [aux_sym__metadata_repeat1] = "_metadata_repeat1",
  [aux_sym_vector_repeat1] = "vector_repeat1",
  [aux_sym__bare_list_repeat1] = "_bare_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__ws] = sym__ws,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_keyword_token1] = aux_sym_keyword_token1,
  [aux_sym_symbol_token1] = aux_sym_symbol_token1,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source] = sym_source,
  [sym__gap] = sym__gap,
  [sym__form] = sym__form,
  [sym__metadata] = sym__metadata,
  [sym_vector] = sym_vector,
  [sym_list] = sym_list,
  [sym__bare_list] = sym__bare_list,
  [sym__bare_vector] = sym__bare_vector,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_keyword_repeat1] = aux_sym_keyword_repeat1,
  [aux_sym__metadata_repeat1] = aux_sym__metadata_repeat1,
  [aux_sym_vector_repeat1] = aux_sym_vector_repeat1,
  [aux_sym__bare_list_repeat1] = aux_sym__bare_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_keyword_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_symbol_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__gap] = {
    .visible = false,
    .named = true,
  },
  [sym__form] = {
    .visible = false,
    .named = true,
  },
  [sym__metadata] = {
    .visible = false,
    .named = true,
  },
  [sym_vector] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__bare_list] = {
    .visible = false,
    .named = true,
  },
  [sym__bare_vector] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_keyword_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__metadata_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_vector_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__bare_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_close = 1,
  field_marker = 2,
  field_name = 3,
  field_open = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_close] = "close",
  [field_marker] = "marker",
  [field_name] = "name",
  [field_open] = "open",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 3},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 1},
  [7] = {.index = 11, .length = 5},
  [8] = {.index = 16, .length = 4},
  [9] = {.index = 20, .length = 3},
  [10] = {.index = 23, .length = 2},
  [11] = {.index = 25, .length = 3},
  [12] = {.index = 28, .length = 2},
  [13] = {.index = 30, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_marker, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [3] =
    {field_close, 0, .inherited = true},
    {field_open, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [6] =
    {field_marker, 0},
    {field_value, 1},
  [8] =
    {field_close, 1},
    {field_open, 0},
  [10] =
    {field_value, 0},
  [11] =
    {field_close, 1, .inherited = true},
    {field_marker, 0, .inherited = true},
    {field_open, 1, .inherited = true},
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [16] =
    {field_marker, 0, .inherited = true},
    {field_marker, 1, .inherited = true},
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [20] =
    {field_marker, 0},
    {field_value, 1},
    {field_value, 2},
  [23] =
    {field_marker, 0},
    {field_value, 2},
  [25] =
    {field_close, 2},
    {field_open, 0},
    {field_value, 1, .inherited = true},
  [28] =
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [30] =
    {field_marker, 0},
    {field_value, 2},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 2,
  [6] = 6,
  [7] = 4,
  [8] = 4,
  [9] = 9,
  [10] = 6,
  [11] = 11,
  [12] = 6,
  [13] = 9,
  [14] = 14,
  [15] = 15,
  [16] = 9,
  [17] = 15,
  [18] = 18,
  [19] = 18,
  [20] = 20,
  [21] = 18,
  [22] = 20,
  [23] = 20,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 24,
  [31] = 31,
  [32] = 29,
  [33] = 33,
  [34] = 25,
  [35] = 29,
  [36] = 28,
  [37] = 31,
  [38] = 25,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 26,
  [43] = 27,
  [44] = 33,
  [45] = 33,
  [46] = 40,
  [47] = 41,
  [48] = 28,
  [49] = 24,
  [50] = 31,
  [51] = 39,
  [52] = 39,
  [53] = 41,
  [54] = 26,
  [55] = 27,
  [56] = 56,
  [57] = 20,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 66,
  [68] = 68,
  [69] = 69,
  [70] = 66,
  [71] = 71,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '\f') ADVANCE(9);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == '[') ADVANCE(19);
      if (lookahead == ']') ADVANCE(20);
      if (lookahead == '^') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '\f') ADVANCE(9);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == '[') ADVANCE(19);
      if (lookahead == ']') ADVANCE(20);
      if (lookahead == '^') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '\f') ADVANCE(9);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == '[') ADVANCE(18);
      if (lookahead == '^') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(11);
      END_STATE();
    case 5:
      if (eof) ADVANCE(7);
      if (lookahead == '\f') ADVANCE(9);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == '[') ADVANCE(19);
      if (lookahead == '^') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(12);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '\f') ADVANCE(9);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == '[') ADVANCE(19);
      if (lookahead == '^') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(13);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\f') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_keyword_token1);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_keyword_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_CARET);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(13);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(13);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(13);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 6},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 6},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__ws] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_keyword_token1] = ACTIONS(1),
    [aux_sym_symbol_token1] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [1] = {
    [sym_source] = STATE(71),
    [sym__gap] = STATE(11),
    [sym__form] = STATE(11),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(11),
    [sym_list] = STATE(11),
    [sym__bare_list] = STATE(30),
    [sym__bare_vector] = STATE(31),
    [aux_sym_source_repeat1] = STATE(11),
    [aux_sym_vector_repeat1] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(7),
    [aux_sym_symbol_token1] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [2] = {
    [sym__gap] = STATE(9),
    [sym__form] = STATE(46),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(46),
    [sym_list] = STATE(46),
    [sym__bare_list] = STATE(24),
    [sym__bare_vector] = STATE(37),
    [aux_sym_vector_repeat1] = STATE(32),
    [aux_sym__bare_list_repeat1] = STATE(9),
    [sym__ws] = ACTIONS(17),
    [anon_sym_COLON] = ACTIONS(19),
    [aux_sym_symbol_token1] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
  },
  [3] = {
    [sym__gap] = STATE(13),
    [sym__form] = STATE(46),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(46),
    [sym_list] = STATE(46),
    [sym__bare_list] = STATE(24),
    [sym__bare_vector] = STATE(37),
    [aux_sym_vector_repeat1] = STATE(32),
    [aux_sym__bare_list_repeat1] = STATE(13),
    [sym__ws] = ACTIONS(29),
    [anon_sym_COLON] = ACTIONS(19),
    [aux_sym_symbol_token1] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(27),
  },
  [4] = {
    [sym__gap] = STATE(17),
    [sym__form] = STATE(40),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(40),
    [sym_list] = STATE(40),
    [sym__bare_list] = STATE(49),
    [sym__bare_vector] = STATE(50),
    [aux_sym_vector_repeat1] = STATE(29),
    [aux_sym__bare_list_repeat1] = STATE(17),
    [sym__ws] = ACTIONS(33),
    [anon_sym_COLON] = ACTIONS(35),
    [aux_sym_symbol_token1] = ACTIONS(37),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_RBRACK] = ACTIONS(43),
  },
  [5] = {
    [sym__gap] = STATE(16),
    [sym__form] = STATE(46),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(46),
    [sym_list] = STATE(46),
    [sym__bare_list] = STATE(24),
    [sym__bare_vector] = STATE(37),
    [aux_sym_vector_repeat1] = STATE(32),
    [aux_sym__bare_list_repeat1] = STATE(16),
    [sym__ws] = ACTIONS(45),
    [anon_sym_COLON] = ACTIONS(19),
    [aux_sym_symbol_token1] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(27),
  },
  [6] = {
    [sym__gap] = STATE(7),
    [sym__form] = STATE(40),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(40),
    [sym_list] = STATE(40),
    [sym__bare_list] = STATE(49),
    [sym__bare_vector] = STATE(50),
    [aux_sym_vector_repeat1] = STATE(29),
    [aux_sym__bare_list_repeat1] = STATE(7),
    [sym__ws] = ACTIONS(49),
    [anon_sym_COLON] = ACTIONS(35),
    [aux_sym_symbol_token1] = ACTIONS(37),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_RBRACK] = ACTIONS(51),
  },
  [7] = {
    [sym__gap] = STATE(17),
    [sym__form] = STATE(40),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(40),
    [sym_list] = STATE(40),
    [sym__bare_list] = STATE(49),
    [sym__bare_vector] = STATE(50),
    [aux_sym_vector_repeat1] = STATE(29),
    [aux_sym__bare_list_repeat1] = STATE(17),
    [sym__ws] = ACTIONS(33),
    [anon_sym_COLON] = ACTIONS(35),
    [aux_sym_symbol_token1] = ACTIONS(37),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_RBRACK] = ACTIONS(53),
  },
  [8] = {
    [sym__gap] = STATE(17),
    [sym__form] = STATE(40),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(40),
    [sym_list] = STATE(40),
    [sym__bare_list] = STATE(49),
    [sym__bare_vector] = STATE(50),
    [aux_sym_vector_repeat1] = STATE(29),
    [aux_sym__bare_list_repeat1] = STATE(17),
    [sym__ws] = ACTIONS(33),
    [anon_sym_COLON] = ACTIONS(35),
    [aux_sym_symbol_token1] = ACTIONS(37),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_RBRACK] = ACTIONS(55),
  },
  [9] = {
    [sym__gap] = STATE(15),
    [sym__form] = STATE(46),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(46),
    [sym_list] = STATE(46),
    [sym__bare_list] = STATE(24),
    [sym__bare_vector] = STATE(37),
    [aux_sym_vector_repeat1] = STATE(32),
    [aux_sym__bare_list_repeat1] = STATE(15),
    [sym__ws] = ACTIONS(57),
    [anon_sym_COLON] = ACTIONS(19),
    [aux_sym_symbol_token1] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_LBRACK] = ACTIONS(27),
  },
  [10] = {
    [sym__gap] = STATE(8),
    [sym__form] = STATE(40),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(40),
    [sym_list] = STATE(40),
    [sym__bare_list] = STATE(49),
    [sym__bare_vector] = STATE(50),
    [aux_sym_vector_repeat1] = STATE(29),
    [aux_sym__bare_list_repeat1] = STATE(8),
    [sym__ws] = ACTIONS(61),
    [anon_sym_COLON] = ACTIONS(35),
    [aux_sym_symbol_token1] = ACTIONS(37),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_RBRACK] = ACTIONS(63),
  },
  [11] = {
    [sym__gap] = STATE(14),
    [sym__form] = STATE(14),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(14),
    [sym_list] = STATE(14),
    [sym__bare_list] = STATE(30),
    [sym__bare_vector] = STATE(31),
    [aux_sym_source_repeat1] = STATE(14),
    [aux_sym_vector_repeat1] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(65),
    [sym__ws] = ACTIONS(67),
    [anon_sym_COLON] = ACTIONS(7),
    [aux_sym_symbol_token1] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [12] = {
    [sym__gap] = STATE(4),
    [sym__form] = STATE(40),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(40),
    [sym_list] = STATE(40),
    [sym__bare_list] = STATE(49),
    [sym__bare_vector] = STATE(50),
    [aux_sym_vector_repeat1] = STATE(29),
    [aux_sym__bare_list_repeat1] = STATE(4),
    [sym__ws] = ACTIONS(69),
    [anon_sym_COLON] = ACTIONS(35),
    [aux_sym_symbol_token1] = ACTIONS(37),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_RBRACK] = ACTIONS(71),
  },
  [13] = {
    [sym__gap] = STATE(15),
    [sym__form] = STATE(46),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(46),
    [sym_list] = STATE(46),
    [sym__bare_list] = STATE(24),
    [sym__bare_vector] = STATE(37),
    [aux_sym_vector_repeat1] = STATE(32),
    [aux_sym__bare_list_repeat1] = STATE(15),
    [sym__ws] = ACTIONS(57),
    [anon_sym_COLON] = ACTIONS(19),
    [aux_sym_symbol_token1] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(27),
  },
  [14] = {
    [sym__gap] = STATE(14),
    [sym__form] = STATE(14),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(14),
    [sym_list] = STATE(14),
    [sym__bare_list] = STATE(30),
    [sym__bare_vector] = STATE(31),
    [aux_sym_source_repeat1] = STATE(14),
    [aux_sym_vector_repeat1] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(75),
    [sym__ws] = ACTIONS(77),
    [anon_sym_COLON] = ACTIONS(80),
    [aux_sym_symbol_token1] = ACTIONS(83),
    [anon_sym_CARET] = ACTIONS(86),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_LBRACK] = ACTIONS(92),
  },
  [15] = {
    [sym__gap] = STATE(15),
    [sym__form] = STATE(46),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(46),
    [sym_list] = STATE(46),
    [sym__bare_list] = STATE(24),
    [sym__bare_vector] = STATE(37),
    [aux_sym_vector_repeat1] = STATE(32),
    [aux_sym__bare_list_repeat1] = STATE(15),
    [sym__ws] = ACTIONS(95),
    [anon_sym_COLON] = ACTIONS(98),
    [aux_sym_symbol_token1] = ACTIONS(101),
    [anon_sym_CARET] = ACTIONS(104),
    [anon_sym_LPAREN] = ACTIONS(107),
    [anon_sym_RPAREN] = ACTIONS(110),
    [anon_sym_LBRACK] = ACTIONS(112),
  },
  [16] = {
    [sym__gap] = STATE(15),
    [sym__form] = STATE(46),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(46),
    [sym_list] = STATE(46),
    [sym__bare_list] = STATE(24),
    [sym__bare_vector] = STATE(37),
    [aux_sym_vector_repeat1] = STATE(32),
    [aux_sym__bare_list_repeat1] = STATE(15),
    [sym__ws] = ACTIONS(57),
    [anon_sym_COLON] = ACTIONS(19),
    [aux_sym_symbol_token1] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(115),
    [anon_sym_LBRACK] = ACTIONS(27),
  },
  [17] = {
    [sym__gap] = STATE(17),
    [sym__form] = STATE(40),
    [sym__metadata] = STATE(65),
    [sym_vector] = STATE(40),
    [sym_list] = STATE(40),
    [sym__bare_list] = STATE(49),
    [sym__bare_vector] = STATE(50),
    [aux_sym_vector_repeat1] = STATE(29),
    [aux_sym__bare_list_repeat1] = STATE(17),
    [sym__ws] = ACTIONS(117),
    [anon_sym_COLON] = ACTIONS(120),
    [aux_sym_symbol_token1] = ACTIONS(123),
    [anon_sym_CARET] = ACTIONS(104),
    [anon_sym_LPAREN] = ACTIONS(126),
    [anon_sym_LBRACK] = ACTIONS(129),
    [anon_sym_RBRACK] = ACTIONS(110),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(132), 1,
      sym__ws,
    ACTIONS(136), 1,
      aux_sym_keyword_token1,
    STATE(20), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(134), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [18] = 4,
    ACTIONS(132), 1,
      sym__ws,
    ACTIONS(138), 1,
      aux_sym_keyword_token1,
    STATE(22), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(134), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [36] = 4,
    ACTIONS(140), 1,
      sym__ws,
    ACTIONS(144), 1,
      aux_sym_keyword_token1,
    STATE(20), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(142), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [54] = 4,
    ACTIONS(147), 1,
      aux_sym_keyword_token1,
    STATE(23), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(132), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(134), 5,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [72] = 4,
    ACTIONS(140), 1,
      sym__ws,
    ACTIONS(149), 1,
      aux_sym_keyword_token1,
    STATE(22), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(142), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [90] = 4,
    ACTIONS(152), 1,
      aux_sym_keyword_token1,
    STATE(23), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(140), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(142), 5,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [108] = 2,
    ACTIONS(155), 1,
      sym__ws,
    ACTIONS(157), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [120] = 2,
    ACTIONS(159), 1,
      sym__ws,
    ACTIONS(161), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [132] = 2,
    ACTIONS(163), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(165), 5,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [144] = 2,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(169), 5,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [156] = 2,
    ACTIONS(171), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(173), 5,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [168] = 7,
    ACTIONS(175), 1,
      anon_sym_CARET,
    ACTIONS(177), 1,
      anon_sym_LPAREN,
    ACTIONS(179), 1,
      anon_sym_LBRACK,
    STATE(54), 1,
      sym__bare_list,
    STATE(55), 1,
      sym__bare_vector,
    STATE(62), 1,
      aux_sym_vector_repeat1,
    STATE(65), 1,
      sym__metadata,
  [190] = 2,
    ACTIONS(155), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(157), 5,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [202] = 2,
    ACTIONS(181), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(183), 5,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [214] = 7,
    ACTIONS(175), 1,
      anon_sym_CARET,
    ACTIONS(185), 1,
      anon_sym_LPAREN,
    ACTIONS(187), 1,
      anon_sym_LBRACK,
    STATE(42), 1,
      sym__bare_list,
    STATE(43), 1,
      sym__bare_vector,
    STATE(62), 1,
      aux_sym_vector_repeat1,
    STATE(65), 1,
      sym__metadata,
  [236] = 2,
    ACTIONS(189), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(191), 5,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [248] = 2,
    ACTIONS(159), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(161), 5,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [260] = 7,
    ACTIONS(175), 1,
      anon_sym_CARET,
    ACTIONS(193), 1,
      anon_sym_LPAREN,
    ACTIONS(195), 1,
      anon_sym_LBRACK,
    STATE(26), 1,
      sym__bare_list,
    STATE(27), 1,
      sym__bare_vector,
    STATE(62), 1,
      aux_sym_vector_repeat1,
    STATE(65), 1,
      sym__metadata,
  [282] = 2,
    ACTIONS(171), 1,
      sym__ws,
    ACTIONS(173), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [294] = 2,
    ACTIONS(181), 1,
      sym__ws,
    ACTIONS(183), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [306] = 2,
    ACTIONS(159), 1,
      sym__ws,
    ACTIONS(161), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [318] = 2,
    ACTIONS(197), 1,
      sym__ws,
    ACTIONS(199), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [330] = 2,
    ACTIONS(201), 1,
      sym__ws,
    ACTIONS(203), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [342] = 2,
    ACTIONS(205), 1,
      sym__ws,
    ACTIONS(207), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [354] = 2,
    ACTIONS(163), 1,
      sym__ws,
    ACTIONS(165), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [366] = 2,
    ACTIONS(167), 1,
      sym__ws,
    ACTIONS(169), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [378] = 2,
    ACTIONS(189), 1,
      sym__ws,
    ACTIONS(191), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [390] = 2,
    ACTIONS(189), 1,
      sym__ws,
    ACTIONS(191), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [402] = 2,
    ACTIONS(201), 1,
      sym__ws,
    ACTIONS(203), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [414] = 2,
    ACTIONS(205), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(207), 5,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [426] = 2,
    ACTIONS(171), 1,
      sym__ws,
    ACTIONS(173), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [438] = 2,
    ACTIONS(155), 1,
      sym__ws,
    ACTIONS(157), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [450] = 2,
    ACTIONS(181), 1,
      sym__ws,
    ACTIONS(183), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [462] = 2,
    ACTIONS(197), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(199), 5,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [474] = 2,
    ACTIONS(197), 1,
      sym__ws,
    ACTIONS(199), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [486] = 2,
    ACTIONS(205), 1,
      sym__ws,
    ACTIONS(207), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [498] = 2,
    ACTIONS(163), 1,
      sym__ws,
    ACTIONS(165), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [510] = 2,
    ACTIONS(167), 1,
      sym__ws,
    ACTIONS(169), 6,
      anon_sym_COLON,
      aux_sym_symbol_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [522] = 4,
    ACTIONS(209), 1,
      sym__ws,
    ACTIONS(211), 1,
      anon_sym_COLON,
    ACTIONS(213), 1,
      aux_sym_symbol_token1,
    STATE(59), 2,
      sym__gap,
      aux_sym__metadata_repeat1,
  [536] = 3,
    ACTIONS(215), 1,
      aux_sym_keyword_token1,
    STATE(57), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(140), 3,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [548] = 3,
    ACTIONS(218), 1,
      aux_sym_keyword_token1,
    STATE(57), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(220), 3,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [560] = 3,
    ACTIONS(222), 1,
      sym__ws,
    ACTIONS(225), 2,
      anon_sym_COLON,
      aux_sym_symbol_token1,
    STATE(59), 2,
      sym__gap,
      aux_sym__metadata_repeat1,
  [572] = 3,
    ACTIONS(218), 1,
      aux_sym_keyword_token1,
    STATE(57), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(227), 3,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [584] = 4,
    ACTIONS(229), 1,
      sym__ws,
    ACTIONS(231), 1,
      anon_sym_COLON,
    ACTIONS(233), 1,
      aux_sym_symbol_token1,
    STATE(56), 2,
      sym__gap,
      aux_sym__metadata_repeat1,
  [598] = 4,
    ACTIONS(235), 1,
      anon_sym_CARET,
    STATE(62), 1,
      aux_sym_vector_repeat1,
    STATE(65), 1,
      sym__metadata,
    ACTIONS(238), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [612] = 1,
    ACTIONS(240), 3,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [618] = 1,
    ACTIONS(242), 3,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [624] = 1,
    ACTIONS(244), 3,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [630] = 2,
    ACTIONS(246), 1,
      aux_sym_keyword_token1,
    STATE(21), 1,
      aux_sym_keyword_repeat1,
  [637] = 2,
    ACTIONS(248), 1,
      aux_sym_keyword_token1,
    STATE(18), 1,
      aux_sym_keyword_repeat1,
  [644] = 2,
    ACTIONS(250), 1,
      aux_sym_keyword_token1,
    STATE(60), 1,
      aux_sym_keyword_repeat1,
  [651] = 2,
    ACTIONS(252), 1,
      aux_sym_keyword_token1,
    STATE(58), 1,
      aux_sym_keyword_repeat1,
  [658] = 2,
    ACTIONS(254), 1,
      aux_sym_keyword_token1,
    STATE(19), 1,
      aux_sym_keyword_repeat1,
  [665] = 1,
    ACTIONS(256), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(18)] = 0,
  [SMALL_STATE(19)] = 18,
  [SMALL_STATE(20)] = 36,
  [SMALL_STATE(21)] = 54,
  [SMALL_STATE(22)] = 72,
  [SMALL_STATE(23)] = 90,
  [SMALL_STATE(24)] = 108,
  [SMALL_STATE(25)] = 120,
  [SMALL_STATE(26)] = 132,
  [SMALL_STATE(27)] = 144,
  [SMALL_STATE(28)] = 156,
  [SMALL_STATE(29)] = 168,
  [SMALL_STATE(30)] = 190,
  [SMALL_STATE(31)] = 202,
  [SMALL_STATE(32)] = 214,
  [SMALL_STATE(33)] = 236,
  [SMALL_STATE(34)] = 248,
  [SMALL_STATE(35)] = 260,
  [SMALL_STATE(36)] = 282,
  [SMALL_STATE(37)] = 294,
  [SMALL_STATE(38)] = 306,
  [SMALL_STATE(39)] = 318,
  [SMALL_STATE(40)] = 330,
  [SMALL_STATE(41)] = 342,
  [SMALL_STATE(42)] = 354,
  [SMALL_STATE(43)] = 366,
  [SMALL_STATE(44)] = 378,
  [SMALL_STATE(45)] = 390,
  [SMALL_STATE(46)] = 402,
  [SMALL_STATE(47)] = 414,
  [SMALL_STATE(48)] = 426,
  [SMALL_STATE(49)] = 438,
  [SMALL_STATE(50)] = 450,
  [SMALL_STATE(51)] = 462,
  [SMALL_STATE(52)] = 474,
  [SMALL_STATE(53)] = 486,
  [SMALL_STATE(54)] = 498,
  [SMALL_STATE(55)] = 510,
  [SMALL_STATE(56)] = 522,
  [SMALL_STATE(57)] = 536,
  [SMALL_STATE(58)] = 548,
  [SMALL_STATE(59)] = 560,
  [SMALL_STATE(60)] = 572,
  [SMALL_STATE(61)] = 584,
  [SMALL_STATE(62)] = 598,
  [SMALL_STATE(63)] = 612,
  [SMALL_STATE(64)] = 618,
  [SMALL_STATE(65)] = 624,
  [SMALL_STATE(66)] = 630,
  [SMALL_STATE(67)] = 637,
  [SMALL_STATE(68)] = 644,
  [SMALL_STATE(69)] = 651,
  [SMALL_STATE(70)] = 658,
  [SMALL_STATE(71)] = 665,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(14),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(66),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(28),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(61),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(5),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(6),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(15),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(67),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(36),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(61),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(2),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 12),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(10),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(17),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(70),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(48),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(3),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(12),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__form, 2),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__form, 2),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_keyword_repeat1, 2),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_keyword_repeat1, 2),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_keyword_repeat1, 2), SHIFT_REPEAT(20),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_keyword_repeat1, 2), SHIFT_REPEAT(22),
  [152] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_keyword_repeat1, 2), SHIFT_REPEAT(23),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 1, .production_id = 3),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 1, .production_id = 3),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bare_vector, 3, .production_id = 11),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bare_vector, 3, .production_id = 11),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, .production_id = 7),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, .production_id = 7),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 2, .production_id = 7),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 2, .production_id = 7),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__form, 1, .production_id = 1),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__form, 1, .production_id = 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 1, .production_id = 3),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 1, .production_id = 3),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bare_list, 3, .production_id = 11),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bare_list, 3, .production_id = 11),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bare_list, 2, .production_id = 5),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bare_list, 2, .production_id = 5),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__bare_list_repeat1, 1, .production_id = 6),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 1, .production_id = 6),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bare_vector, 2, .production_id = 5),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bare_vector, 2, .production_id = 5),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [215] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_keyword_repeat1, 2), SHIFT_REPEAT(57),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__metadata, 4, .production_id = 13),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__metadata_repeat1, 2), SHIFT_REPEAT(59),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__metadata_repeat1, 2),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__metadata, 3, .production_id = 9),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [235] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, .production_id = 8), SHIFT_REPEAT(61),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, .production_id = 8),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__metadata, 2, .production_id = 4),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__metadata, 3, .production_id = 10),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 1, .production_id = 2),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [256] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_piglet(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
