#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 73
#define LARGE_STATE_COUNT 18
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 13

enum {
  sym__ws = 1,
  anon_sym_COLON = 2,
  aux_sym_keyword_token1 = 3,
  anon_sym_CARET = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_LBRACK = 7,
  anon_sym_RBRACK = 8,
  sym_source = 9,
  sym__gap = 10,
  sym__form = 11,
  sym_symbol1 = 12,
  sym__metadata = 13,
  sym_vector = 14,
  sym_list = 15,
  sym__bare_list = 16,
  sym__bare_vector = 17,
  aux_sym_source_repeat1 = 18,
  aux_sym_keyword_repeat1 = 19,
  aux_sym__metadata_repeat1 = 20,
  aux_sym_vector_repeat1 = 21,
  aux_sym__bare_list_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__ws] = "_ws",
  [anon_sym_COLON] = ":",
  [aux_sym_keyword_token1] = "keyword_token1",
  [anon_sym_CARET] = "^",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source] = "source",
  [sym__gap] = "_gap",
  [sym__form] = "_form",
  [sym_symbol1] = "symbol1",
  [sym__metadata] = "_metadata",
  [sym_vector] = "vector",
  [sym_list] = "list",
  [sym__bare_list] = "_bare_list",
  [sym__bare_vector] = "_bare_vector",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_keyword_repeat1] = "keyword_repeat1",
  [aux_sym__metadata_repeat1] = "_metadata_repeat1",
  [aux_sym_vector_repeat1] = "vector_repeat1",
  [aux_sym__bare_list_repeat1] = "_bare_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__ws] = sym__ws,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_keyword_token1] = aux_sym_keyword_token1,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source] = sym_source,
  [sym__gap] = sym__gap,
  [sym__form] = sym__form,
  [sym_symbol1] = sym_symbol1,
  [sym__metadata] = sym__metadata,
  [sym_vector] = sym_vector,
  [sym_list] = sym_list,
  [sym__bare_list] = sym__bare_list,
  [sym__bare_vector] = sym__bare_vector,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_keyword_repeat1] = aux_sym_keyword_repeat1,
  [aux_sym__metadata_repeat1] = aux_sym__metadata_repeat1,
  [aux_sym_vector_repeat1] = aux_sym_vector_repeat1,
  [aux_sym__bare_list_repeat1] = aux_sym__bare_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_keyword_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__gap] = {
    .visible = false,
    .named = true,
  },
  [sym__form] = {
    .visible = false,
    .named = true,
  },
  [sym_symbol1] = {
    .visible = true,
    .named = true,
  },
  [sym__metadata] = {
    .visible = false,
    .named = true,
  },
  [sym_vector] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__bare_list] = {
    .visible = false,
    .named = true,
  },
  [sym__bare_vector] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_keyword_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__metadata_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_vector_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__bare_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_close = 1,
  field_marker = 2,
  field_open = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_close] = "close",
  [field_marker] = "marker",
  [field_open] = "open",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 2},
  [4] = {.index = 7, .length = 2},
  [5] = {.index = 9, .length = 1},
  [6] = {.index = 10, .length = 5},
  [7] = {.index = 15, .length = 4},
  [8] = {.index = 19, .length = 3},
  [9] = {.index = 22, .length = 2},
  [10] = {.index = 24, .length = 3},
  [11] = {.index = 27, .length = 2},
  [12] = {.index = 29, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_marker, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [2] =
    {field_close, 0, .inherited = true},
    {field_open, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [5] =
    {field_marker, 0},
    {field_value, 1},
  [7] =
    {field_close, 1},
    {field_open, 0},
  [9] =
    {field_value, 0},
  [10] =
    {field_close, 1, .inherited = true},
    {field_marker, 0, .inherited = true},
    {field_open, 1, .inherited = true},
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [15] =
    {field_marker, 0, .inherited = true},
    {field_marker, 1, .inherited = true},
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [19] =
    {field_marker, 0},
    {field_value, 1},
    {field_value, 2},
  [22] =
    {field_marker, 0},
    {field_value, 2},
  [24] =
    {field_close, 2},
    {field_open, 0},
    {field_value, 1, .inherited = true},
  [27] =
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [29] =
    {field_marker, 0},
    {field_value, 2},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 4,
  [7] = 4,
  [8] = 8,
  [9] = 3,
  [10] = 10,
  [11] = 11,
  [12] = 8,
  [13] = 11,
  [14] = 2,
  [15] = 15,
  [16] = 8,
  [17] = 3,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 20,
  [22] = 19,
  [23] = 19,
  [24] = 18,
  [25] = 18,
  [26] = 20,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 27,
  [33] = 33,
  [34] = 34,
  [35] = 30,
  [36] = 31,
  [37] = 30,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 39,
  [43] = 28,
  [44] = 44,
  [45] = 33,
  [46] = 44,
  [47] = 34,
  [48] = 31,
  [49] = 27,
  [50] = 34,
  [51] = 41,
  [52] = 39,
  [53] = 41,
  [54] = 40,
  [55] = 28,
  [56] = 44,
  [57] = 33,
  [58] = 58,
  [59] = 19,
  [60] = 20,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 67,
  [69] = 69,
  [70] = 67,
  [71] = 71,
  [72] = 72,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '\f') ADVANCE(7);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '[') ADVANCE(13);
      if (lookahead == ']') ADVANCE(14);
      if (lookahead == '^') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == '\f') ADVANCE(7);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == '[') ADVANCE(13);
      if (lookahead == '^') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(9);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '\f') ADVANCE(7);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == '[') ADVANCE(13);
      if (lookahead == '^') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead == '!' ||
          ('$' <= lookahead && lookahead <= '&') ||
          ('*' <= lookahead && lookahead <= '_') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '|') ADVANCE(9);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\f') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_keyword_token1);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__ws] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_keyword_token1] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [1] = {
    [sym_source] = STATE(72),
    [sym__gap] = STATE(10),
    [sym__form] = STATE(10),
    [sym_symbol1] = STATE(10),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(10),
    [sym_list] = STATE(10),
    [sym__bare_list] = STATE(31),
    [sym__bare_vector] = STATE(32),
    [aux_sym_source_repeat1] = STATE(10),
    [aux_sym_keyword_repeat1] = STATE(21),
    [aux_sym_vector_repeat1] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__ws] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(7),
    [aux_sym_keyword_token1] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [2] = {
    [sym__gap] = STATE(8),
    [sym__form] = STATE(40),
    [sym_symbol1] = STATE(40),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(40),
    [sym_list] = STATE(40),
    [sym__bare_list] = STATE(48),
    [sym__bare_vector] = STATE(49),
    [aux_sym_keyword_repeat1] = STATE(26),
    [aux_sym_vector_repeat1] = STATE(30),
    [aux_sym__bare_list_repeat1] = STATE(8),
    [sym__ws] = ACTIONS(17),
    [anon_sym_COLON] = ACTIONS(19),
    [aux_sym_keyword_token1] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(27),
  },
  [3] = {
    [sym__gap] = STATE(11),
    [sym__form] = STATE(54),
    [sym_symbol1] = STATE(54),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(54),
    [sym_list] = STATE(54),
    [sym__bare_list] = STATE(36),
    [sym__bare_vector] = STATE(27),
    [aux_sym_keyword_repeat1] = STATE(20),
    [aux_sym_vector_repeat1] = STATE(37),
    [aux_sym__bare_list_repeat1] = STATE(11),
    [sym__ws] = ACTIONS(29),
    [anon_sym_COLON] = ACTIONS(31),
    [aux_sym_keyword_token1] = ACTIONS(33),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
  },
  [4] = {
    [sym__gap] = STATE(17),
    [sym__form] = STATE(54),
    [sym_symbol1] = STATE(54),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(54),
    [sym_list] = STATE(54),
    [sym__bare_list] = STATE(36),
    [sym__bare_vector] = STATE(27),
    [aux_sym_keyword_repeat1] = STATE(20),
    [aux_sym_vector_repeat1] = STATE(37),
    [aux_sym__bare_list_repeat1] = STATE(17),
    [sym__ws] = ACTIONS(41),
    [anon_sym_COLON] = ACTIONS(31),
    [aux_sym_keyword_token1] = ACTIONS(33),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(39),
  },
  [5] = {
    [sym__gap] = STATE(16),
    [sym__form] = STATE(40),
    [sym_symbol1] = STATE(40),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(40),
    [sym_list] = STATE(40),
    [sym__bare_list] = STATE(48),
    [sym__bare_vector] = STATE(49),
    [aux_sym_keyword_repeat1] = STATE(26),
    [aux_sym_vector_repeat1] = STATE(30),
    [aux_sym__bare_list_repeat1] = STATE(16),
    [sym__ws] = ACTIONS(45),
    [anon_sym_COLON] = ACTIONS(19),
    [aux_sym_keyword_token1] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(47),
  },
  [6] = {
    [sym__gap] = STATE(9),
    [sym__form] = STATE(54),
    [sym_symbol1] = STATE(54),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(54),
    [sym_list] = STATE(54),
    [sym__bare_list] = STATE(36),
    [sym__bare_vector] = STATE(27),
    [aux_sym_keyword_repeat1] = STATE(20),
    [aux_sym_vector_repeat1] = STATE(37),
    [aux_sym__bare_list_repeat1] = STATE(9),
    [sym__ws] = ACTIONS(49),
    [anon_sym_COLON] = ACTIONS(31),
    [aux_sym_keyword_token1] = ACTIONS(33),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(51),
    [anon_sym_LBRACK] = ACTIONS(39),
  },
  [7] = {
    [sym__gap] = STATE(3),
    [sym__form] = STATE(54),
    [sym_symbol1] = STATE(54),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(54),
    [sym_list] = STATE(54),
    [sym__bare_list] = STATE(36),
    [sym__bare_vector] = STATE(27),
    [aux_sym_keyword_repeat1] = STATE(20),
    [aux_sym_vector_repeat1] = STATE(37),
    [aux_sym__bare_list_repeat1] = STATE(3),
    [sym__ws] = ACTIONS(53),
    [anon_sym_COLON] = ACTIONS(31),
    [aux_sym_keyword_token1] = ACTIONS(33),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(39),
  },
  [8] = {
    [sym__gap] = STATE(13),
    [sym__form] = STATE(40),
    [sym_symbol1] = STATE(40),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(40),
    [sym_list] = STATE(40),
    [sym__bare_list] = STATE(48),
    [sym__bare_vector] = STATE(49),
    [aux_sym_keyword_repeat1] = STATE(26),
    [aux_sym_vector_repeat1] = STATE(30),
    [aux_sym__bare_list_repeat1] = STATE(13),
    [sym__ws] = ACTIONS(57),
    [anon_sym_COLON] = ACTIONS(19),
    [aux_sym_keyword_token1] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(59),
  },
  [9] = {
    [sym__gap] = STATE(11),
    [sym__form] = STATE(54),
    [sym_symbol1] = STATE(54),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(54),
    [sym_list] = STATE(54),
    [sym__bare_list] = STATE(36),
    [sym__bare_vector] = STATE(27),
    [aux_sym_keyword_repeat1] = STATE(20),
    [aux_sym_vector_repeat1] = STATE(37),
    [aux_sym__bare_list_repeat1] = STATE(11),
    [sym__ws] = ACTIONS(29),
    [anon_sym_COLON] = ACTIONS(31),
    [aux_sym_keyword_token1] = ACTIONS(33),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(39),
  },
  [10] = {
    [sym__gap] = STATE(15),
    [sym__form] = STATE(15),
    [sym_symbol1] = STATE(15),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(15),
    [sym_list] = STATE(15),
    [sym__bare_list] = STATE(31),
    [sym__bare_vector] = STATE(32),
    [aux_sym_source_repeat1] = STATE(15),
    [aux_sym_keyword_repeat1] = STATE(21),
    [aux_sym_vector_repeat1] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(63),
    [sym__ws] = ACTIONS(65),
    [anon_sym_COLON] = ACTIONS(7),
    [aux_sym_keyword_token1] = ACTIONS(9),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
  },
  [11] = {
    [sym__gap] = STATE(11),
    [sym__form] = STATE(54),
    [sym_symbol1] = STATE(54),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(54),
    [sym_list] = STATE(54),
    [sym__bare_list] = STATE(36),
    [sym__bare_vector] = STATE(27),
    [aux_sym_keyword_repeat1] = STATE(20),
    [aux_sym_vector_repeat1] = STATE(37),
    [aux_sym__bare_list_repeat1] = STATE(11),
    [sym__ws] = ACTIONS(67),
    [anon_sym_COLON] = ACTIONS(70),
    [aux_sym_keyword_token1] = ACTIONS(73),
    [anon_sym_CARET] = ACTIONS(76),
    [anon_sym_LPAREN] = ACTIONS(79),
    [anon_sym_RPAREN] = ACTIONS(82),
    [anon_sym_LBRACK] = ACTIONS(84),
  },
  [12] = {
    [sym__gap] = STATE(13),
    [sym__form] = STATE(40),
    [sym_symbol1] = STATE(40),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(40),
    [sym_list] = STATE(40),
    [sym__bare_list] = STATE(48),
    [sym__bare_vector] = STATE(49),
    [aux_sym_keyword_repeat1] = STATE(26),
    [aux_sym_vector_repeat1] = STATE(30),
    [aux_sym__bare_list_repeat1] = STATE(13),
    [sym__ws] = ACTIONS(57),
    [anon_sym_COLON] = ACTIONS(19),
    [aux_sym_keyword_token1] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(87),
  },
  [13] = {
    [sym__gap] = STATE(13),
    [sym__form] = STATE(40),
    [sym_symbol1] = STATE(40),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(40),
    [sym_list] = STATE(40),
    [sym__bare_list] = STATE(48),
    [sym__bare_vector] = STATE(49),
    [aux_sym_keyword_repeat1] = STATE(26),
    [aux_sym_vector_repeat1] = STATE(30),
    [aux_sym__bare_list_repeat1] = STATE(13),
    [sym__ws] = ACTIONS(89),
    [anon_sym_COLON] = ACTIONS(92),
    [aux_sym_keyword_token1] = ACTIONS(95),
    [anon_sym_CARET] = ACTIONS(76),
    [anon_sym_LPAREN] = ACTIONS(98),
    [anon_sym_LBRACK] = ACTIONS(101),
    [anon_sym_RBRACK] = ACTIONS(82),
  },
  [14] = {
    [sym__gap] = STATE(12),
    [sym__form] = STATE(40),
    [sym_symbol1] = STATE(40),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(40),
    [sym_list] = STATE(40),
    [sym__bare_list] = STATE(48),
    [sym__bare_vector] = STATE(49),
    [aux_sym_keyword_repeat1] = STATE(26),
    [aux_sym_vector_repeat1] = STATE(30),
    [aux_sym__bare_list_repeat1] = STATE(12),
    [sym__ws] = ACTIONS(104),
    [anon_sym_COLON] = ACTIONS(19),
    [aux_sym_keyword_token1] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(106),
  },
  [15] = {
    [sym__gap] = STATE(15),
    [sym__form] = STATE(15),
    [sym_symbol1] = STATE(15),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(15),
    [sym_list] = STATE(15),
    [sym__bare_list] = STATE(31),
    [sym__bare_vector] = STATE(32),
    [aux_sym_source_repeat1] = STATE(15),
    [aux_sym_keyword_repeat1] = STATE(21),
    [aux_sym_vector_repeat1] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(108),
    [sym__ws] = ACTIONS(110),
    [anon_sym_COLON] = ACTIONS(113),
    [aux_sym_keyword_token1] = ACTIONS(116),
    [anon_sym_CARET] = ACTIONS(119),
    [anon_sym_LPAREN] = ACTIONS(122),
    [anon_sym_LBRACK] = ACTIONS(125),
  },
  [16] = {
    [sym__gap] = STATE(13),
    [sym__form] = STATE(40),
    [sym_symbol1] = STATE(40),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(40),
    [sym_list] = STATE(40),
    [sym__bare_list] = STATE(48),
    [sym__bare_vector] = STATE(49),
    [aux_sym_keyword_repeat1] = STATE(26),
    [aux_sym_vector_repeat1] = STATE(30),
    [aux_sym__bare_list_repeat1] = STATE(13),
    [sym__ws] = ACTIONS(57),
    [anon_sym_COLON] = ACTIONS(19),
    [aux_sym_keyword_token1] = ACTIONS(21),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(128),
  },
  [17] = {
    [sym__gap] = STATE(11),
    [sym__form] = STATE(54),
    [sym_symbol1] = STATE(54),
    [sym__metadata] = STATE(66),
    [sym_vector] = STATE(54),
    [sym_list] = STATE(54),
    [sym__bare_list] = STATE(36),
    [sym__bare_vector] = STATE(27),
    [aux_sym_keyword_repeat1] = STATE(20),
    [aux_sym_vector_repeat1] = STATE(37),
    [aux_sym__bare_list_repeat1] = STATE(11),
    [sym__ws] = ACTIONS(29),
    [anon_sym_COLON] = ACTIONS(31),
    [aux_sym_keyword_token1] = ACTIONS(33),
    [anon_sym_CARET] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(130),
    [anon_sym_LBRACK] = ACTIONS(39),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(132), 1,
      sym__ws,
    STATE(22), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(134), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [15] = 4,
    ACTIONS(136), 1,
      sym__ws,
    ACTIONS(140), 1,
      aux_sym_keyword_token1,
    STATE(19), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(138), 5,
      anon_sym_COLON,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [32] = 3,
    ACTIONS(143), 1,
      sym__ws,
    STATE(19), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(145), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [47] = 3,
    STATE(23), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(143), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(145), 5,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [62] = 4,
    ACTIONS(136), 1,
      sym__ws,
    ACTIONS(147), 1,
      aux_sym_keyword_token1,
    STATE(22), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(138), 5,
      anon_sym_COLON,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [79] = 4,
    ACTIONS(150), 1,
      aux_sym_keyword_token1,
    STATE(23), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(136), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(138), 4,
      anon_sym_COLON,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [96] = 3,
    STATE(23), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(132), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(134), 5,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [111] = 3,
    ACTIONS(132), 1,
      sym__ws,
    STATE(19), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(134), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [126] = 3,
    ACTIONS(143), 1,
      sym__ws,
    STATE(22), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(145), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [141] = 2,
    ACTIONS(153), 1,
      sym__ws,
    ACTIONS(155), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [153] = 2,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(159), 5,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [165] = 6,
    ACTIONS(161), 1,
      sym__ws,
    ACTIONS(163), 1,
      anon_sym_COLON,
    ACTIONS(165), 1,
      aux_sym_keyword_token1,
    STATE(60), 1,
      aux_sym_keyword_repeat1,
    STATE(64), 1,
      sym_symbol1,
    STATE(38), 2,
      sym__gap,
      aux_sym__metadata_repeat1,
  [185] = 7,
    ACTIONS(167), 1,
      anon_sym_CARET,
    ACTIONS(169), 1,
      anon_sym_LPAREN,
    ACTIONS(171), 1,
      anon_sym_LBRACK,
    STATE(55), 1,
      sym__bare_list,
    STATE(56), 1,
      sym__bare_vector,
    STATE(58), 1,
      aux_sym_vector_repeat1,
    STATE(66), 1,
      sym__metadata,
  [207] = 2,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(175), 5,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [219] = 2,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(155), 5,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [231] = 2,
    ACTIONS(177), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(179), 5,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [243] = 2,
    ACTIONS(181), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(183), 5,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [255] = 7,
    ACTIONS(167), 1,
      anon_sym_CARET,
    ACTIONS(185), 1,
      anon_sym_LPAREN,
    ACTIONS(187), 1,
      anon_sym_LBRACK,
    STATE(28), 1,
      sym__bare_list,
    STATE(46), 1,
      sym__bare_vector,
    STATE(58), 1,
      aux_sym_vector_repeat1,
    STATE(66), 1,
      sym__metadata,
  [277] = 2,
    ACTIONS(173), 1,
      sym__ws,
    ACTIONS(175), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [289] = 7,
    ACTIONS(167), 1,
      anon_sym_CARET,
    ACTIONS(189), 1,
      anon_sym_LPAREN,
    ACTIONS(191), 1,
      anon_sym_LBRACK,
    STATE(43), 1,
      sym__bare_list,
    STATE(44), 1,
      sym__bare_vector,
    STATE(58), 1,
      aux_sym_vector_repeat1,
    STATE(66), 1,
      sym__metadata,
  [311] = 6,
    ACTIONS(165), 1,
      aux_sym_keyword_token1,
    ACTIONS(193), 1,
      sym__ws,
    ACTIONS(195), 1,
      anon_sym_COLON,
    STATE(60), 1,
      aux_sym_keyword_repeat1,
    STATE(65), 1,
      sym_symbol1,
    STATE(62), 2,
      sym__gap,
      aux_sym__metadata_repeat1,
  [331] = 2,
    ACTIONS(197), 1,
      sym__ws,
    ACTIONS(199), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [343] = 2,
    ACTIONS(201), 1,
      sym__ws,
    ACTIONS(203), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [355] = 2,
    ACTIONS(205), 1,
      sym__ws,
    ACTIONS(207), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [367] = 2,
    ACTIONS(197), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(199), 5,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [379] = 2,
    ACTIONS(157), 1,
      sym__ws,
    ACTIONS(159), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [391] = 2,
    ACTIONS(209), 1,
      sym__ws,
    ACTIONS(211), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [403] = 2,
    ACTIONS(177), 1,
      sym__ws,
    ACTIONS(179), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [415] = 2,
    ACTIONS(209), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(211), 5,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [427] = 2,
    ACTIONS(181), 1,
      sym__ws,
    ACTIONS(183), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [439] = 2,
    ACTIONS(173), 1,
      sym__ws,
    ACTIONS(175), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [451] = 2,
    ACTIONS(153), 1,
      sym__ws,
    ACTIONS(155), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [463] = 2,
    ACTIONS(181), 1,
      sym__ws,
    ACTIONS(183), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [475] = 2,
    ACTIONS(205), 2,
      ts_builtin_sym_end,
      sym__ws,
    ACTIONS(207), 5,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [487] = 2,
    ACTIONS(197), 1,
      sym__ws,
    ACTIONS(199), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [499] = 2,
    ACTIONS(205), 1,
      sym__ws,
    ACTIONS(207), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [511] = 2,
    ACTIONS(201), 1,
      sym__ws,
    ACTIONS(203), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
  [523] = 2,
    ACTIONS(157), 1,
      sym__ws,
    ACTIONS(159), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [535] = 2,
    ACTIONS(209), 1,
      sym__ws,
    ACTIONS(211), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [547] = 2,
    ACTIONS(177), 1,
      sym__ws,
    ACTIONS(179), 6,
      anon_sym_COLON,
      aux_sym_keyword_token1,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [559] = 4,
    ACTIONS(213), 1,
      anon_sym_CARET,
    STATE(58), 1,
      aux_sym_vector_repeat1,
    STATE(66), 1,
      sym__metadata,
    ACTIONS(216), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [573] = 3,
    ACTIONS(218), 1,
      aux_sym_keyword_token1,
    STATE(59), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(136), 3,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [585] = 3,
    ACTIONS(221), 1,
      aux_sym_keyword_token1,
    STATE(59), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(143), 3,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [597] = 3,
    ACTIONS(221), 1,
      aux_sym_keyword_token1,
    STATE(59), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(223), 3,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [609] = 3,
    ACTIONS(225), 1,
      sym__ws,
    ACTIONS(228), 2,
      anon_sym_COLON,
      aux_sym_keyword_token1,
    STATE(62), 2,
      sym__gap,
      aux_sym__metadata_repeat1,
  [621] = 3,
    ACTIONS(221), 1,
      aux_sym_keyword_token1,
    STATE(59), 1,
      aux_sym_keyword_repeat1,
    ACTIONS(230), 3,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [633] = 1,
    ACTIONS(232), 3,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [639] = 1,
    ACTIONS(234), 3,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [645] = 1,
    ACTIONS(236), 3,
      anon_sym_CARET,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [651] = 2,
    ACTIONS(238), 1,
      aux_sym_keyword_token1,
    STATE(24), 1,
      aux_sym_keyword_repeat1,
  [658] = 2,
    ACTIONS(240), 1,
      aux_sym_keyword_token1,
    STATE(25), 1,
      aux_sym_keyword_repeat1,
  [665] = 2,
    ACTIONS(242), 1,
      aux_sym_keyword_token1,
    STATE(63), 1,
      aux_sym_keyword_repeat1,
  [672] = 2,
    ACTIONS(244), 1,
      aux_sym_keyword_token1,
    STATE(18), 1,
      aux_sym_keyword_repeat1,
  [679] = 2,
    ACTIONS(246), 1,
      aux_sym_keyword_token1,
    STATE(61), 1,
      aux_sym_keyword_repeat1,
  [686] = 1,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(18)] = 0,
  [SMALL_STATE(19)] = 15,
  [SMALL_STATE(20)] = 32,
  [SMALL_STATE(21)] = 47,
  [SMALL_STATE(22)] = 62,
  [SMALL_STATE(23)] = 79,
  [SMALL_STATE(24)] = 96,
  [SMALL_STATE(25)] = 111,
  [SMALL_STATE(26)] = 126,
  [SMALL_STATE(27)] = 141,
  [SMALL_STATE(28)] = 153,
  [SMALL_STATE(29)] = 165,
  [SMALL_STATE(30)] = 185,
  [SMALL_STATE(31)] = 207,
  [SMALL_STATE(32)] = 219,
  [SMALL_STATE(33)] = 231,
  [SMALL_STATE(34)] = 243,
  [SMALL_STATE(35)] = 255,
  [SMALL_STATE(36)] = 277,
  [SMALL_STATE(37)] = 289,
  [SMALL_STATE(38)] = 311,
  [SMALL_STATE(39)] = 331,
  [SMALL_STATE(40)] = 343,
  [SMALL_STATE(41)] = 355,
  [SMALL_STATE(42)] = 367,
  [SMALL_STATE(43)] = 379,
  [SMALL_STATE(44)] = 391,
  [SMALL_STATE(45)] = 403,
  [SMALL_STATE(46)] = 415,
  [SMALL_STATE(47)] = 427,
  [SMALL_STATE(48)] = 439,
  [SMALL_STATE(49)] = 451,
  [SMALL_STATE(50)] = 463,
  [SMALL_STATE(51)] = 475,
  [SMALL_STATE(52)] = 487,
  [SMALL_STATE(53)] = 499,
  [SMALL_STATE(54)] = 511,
  [SMALL_STATE(55)] = 523,
  [SMALL_STATE(56)] = 535,
  [SMALL_STATE(57)] = 547,
  [SMALL_STATE(58)] = 559,
  [SMALL_STATE(59)] = 573,
  [SMALL_STATE(60)] = 585,
  [SMALL_STATE(61)] = 597,
  [SMALL_STATE(62)] = 609,
  [SMALL_STATE(63)] = 621,
  [SMALL_STATE(64)] = 633,
  [SMALL_STATE(65)] = 639,
  [SMALL_STATE(66)] = 645,
  [SMALL_STATE(67)] = 651,
  [SMALL_STATE(68)] = 658,
  [SMALL_STATE(69)] = 665,
  [SMALL_STATE(70)] = 672,
  [SMALL_STATE(71)] = 679,
  [SMALL_STATE(72)] = 686,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 11), SHIFT_REPEAT(11),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 11), SHIFT_REPEAT(68),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 11), SHIFT_REPEAT(20),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 11), SHIFT_REPEAT(29),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 11), SHIFT_REPEAT(6),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 11),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 11), SHIFT_REPEAT(2),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 11), SHIFT_REPEAT(13),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 11), SHIFT_REPEAT(70),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 11), SHIFT_REPEAT(26),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 11), SHIFT_REPEAT(7),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 2, .production_id = 11), SHIFT_REPEAT(14),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(15),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(67),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(21),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(29),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(4),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2), SHIFT_REPEAT(5),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__form, 2),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__form, 2),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_keyword_repeat1, 2),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_keyword_repeat1, 2),
  [140] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_keyword_repeat1, 2), SHIFT_REPEAT(19),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol1, 1),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol1, 1),
  [147] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_keyword_repeat1, 2), SHIFT_REPEAT(22),
  [150] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_keyword_repeat1, 2), SHIFT_REPEAT(23),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 1, .production_id = 2),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 1, .production_id = 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, .production_id = 6),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, .production_id = 6),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 1, .production_id = 2),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 1, .production_id = 2),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bare_list, 3, .production_id = 10),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bare_list, 3, .production_id = 10),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bare_vector, 3, .production_id = 10),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bare_vector, 3, .production_id = 10),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bare_list, 2, .production_id = 4),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bare_list, 2, .production_id = 4),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__bare_list_repeat1, 1, .production_id = 5),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__bare_list_repeat1, 1, .production_id = 5),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bare_vector, 2, .production_id = 4),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bare_vector, 2, .production_id = 4),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 2, .production_id = 6),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 2, .production_id = 6),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, .production_id = 7), SHIFT_REPEAT(29),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, .production_id = 7),
  [218] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_keyword_repeat1, 2), SHIFT_REPEAT(59),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__metadata, 4, .production_id = 12),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__metadata_repeat1, 2), SHIFT_REPEAT(62),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__metadata_repeat1, 2),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__metadata, 3, .production_id = 8),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__metadata, 2, .production_id = 3),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__metadata, 3, .production_id = 9),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 1, .production_id = 1),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [248] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_piglet(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
